### ISSUE TITLE
duiker: Moving up with C-p or the up arrow reruns the previous command

### ISSUE THREAD

**Issue by ryjm** [Fang-/suite#1] opened 2020-09-23 03:41 UTC
This is probably be a shoe related thing, and not a huge deal, but I'd like to be able to move through previous commands without them immediately running. I.e, if I hit up and my last command was +magnet, it will try and resubmit that torrent. Same with any other command. C-r does work though.

Maybe there needs to be a 'history search' toggle that disables the run on single key flag?

**Comment by Fang-** [comment] 2020-09-25 10:43
> Maybe there needs to be a 'history search' toggle that disables the run on single key flag?

Actually, shoe might be able to just say, "[adding to history?](https://github.com/urbit/urbit/blob/9efa389e5ae3ed679a52653fc536524e2d0c6461/pkg/arvo/lib/shoe.hoon#L284) only do that when the command wasn't auto-run". I'll give this a try!

**Comment by Fang-** [comment] 2020-09-26 00:16
> if I hit up and my last command was +magnet

Actually, kind of surprised about this specifically. Cannot reproduce, magnet link submissions don't auto-run in the first place...

In any case, fix incoming in urbit/urbit#3591!

**Comment by Fang-** [comment] 2020-09-29 09:23
Closing as urbit/urbit#3591 got merged and will be included in the next OTA.

**Closed as completed by Fang-** 2020-09-29 09:23 UTC
